# fly.toml app configuration file generated for academia on 2023-11-05T15:44:46-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "academia"
primary_region = "scl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
